### ISSUE TITLE
Component Library

### ISSUE THREAD

**Issue by 3dxp** [COSC481W-2022Winter/capstone-hackmcx#10]
Choose and integrate a component library with the front end.

Acceptance criteria:
- Before the sprint is over the team will decide on a react component library to use.
- Before the sprint is over the component library will be used to construct custom components for the web frontend. (Create-react-app)
- Wen the user loads the web page the following components will be present in the web app:
  - layout
  - button
  - textbox

Tasks:
- [x] decide a list of candidate libraries /Everyone
- [x] everyone researches/tries about the libraries /Everyone
- [x] team has a 15-min ish meeting to discuss /Everyone 
- [x] decide and use the library in a demo /Everyone
- [x] Use the library in the project. /Everyone
  - [x] Use a Layout component. /Everyone
  - [x] Use a button component. /Everyone
  - [x] Use a textbox component. /Everyone

**Comment by acampb65** [comment]
Candidate libraries:
Material UI
Prime React
React-bootstrap
Ant design

**Comment by ahassani93** [comment]
The group decided on using the Material UI component library.
