### ISSUE TITLE
Implement Login Endpoint

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#51]
As a business user I want to persist login credentials  so that valid users can access their own account information and have access to functionalities on the website.

Tasks:
- [x] Update Users to hold Account info [Kevin]
- [x] Update Users controller for saving Account info [Alec]
- [x] Create controller for getting Login info [Kevin, Alec]
- [x] Create the route for POST /login [3dxp]

Acceptance Criteria:

- When a POST request is made against the /v1/users endpoint with a JSON request body with a first name, last name, username, and Account info. A response with the location header set with the relative URL of the created user with a success status code is returned to the client.
- When a POST request is made against the /login endpoint, the login credential is authenticated and the if valid will return a login "token".
- When an invalid Login credentials are given an error code 401 is returned.

**Comment by sjiang1** [comment]
When this PBI is ready for review, you will need to prepare a CURL request.
