### ISSUE TITLE
Adding top Caption to GET /v1/posts Endpoint

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#56]
As a business user I want to persist each Rating for each Caption so that I can retrieve it later to use for data presentation. 

Tasks:

- [x] Update the controller for getting posts /Connor, Alec

Acceptance Criteria:

- If post has Captions the Caption with the highest average rating will be returned as Caption for the Post
- If no caption exists it is not added to the response

**Comment by sjiang1** [comment]
How do you define the rating of a post? Is it an average rating of all the ratings?

**Comment by 3dxp** [comment]
Yes, the rating will be some numeric value that is averaged for every rating that is submitted for a caption on a post.
