### ISSUE TITLE
List Captions sorted by Rating

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#58]
As a fellow web surfer I want to be able to see Captions with highest rating first so that I can view the best jokes easily.

**Acceptance Criteria:**
- "post" react components on the individual post page are listed from highest post caption rating to lowest post caption rating
- Secondary sorting in case more than one post caption has the same rating value

**Tasks:**
- [ ] Get caption ratings from API.
- [ ] Sort captions on the "individual post page" based on caption rating.

**Comment by sjiang1** [comment]
agreed to postpone this for a later sprint.
