### ISSUE TITLE
Implement POST /v1/posts/captions/{id}/_rate Endpoint

### ISSUE THREAD

**Issue by 3dxp** [COSC481W-2022Winter/capstone-hackmcx#59]
As a post viewer, I want my rating to be reflected on the overall ratings of a Caption so that the community can decide which Caption is best.

Implementation Notes:
For this sprint a call to the rating endpoint will update a rolling average on the caption table, however in the future it may be used to keep tract of individual ratings per user. As it is an action that will just update the record and not a resource per say we have a lot of flexibility with how ratings can be handled. 

Task:
- [x] Create controller for updating the rating for each caption /Zhaoyue & Alec
  - [x] The controller should update an average ratings in the caption table. /Zhaoyue & Alec
- [x] Create the route for POST /v1/posts/{id}/captions/{id}/_rate /Connor

Acceptance Criteria:

- When a request is made against the POST /v1/posts/captions/{id}/_rate, the rating's average be updated and a 204 will be returned to the client.
- When an invalid POST request is made against the/v1/posts/captions/{id}/_rate endpoint an error code is returned. (In the 400-499 HTTP response code.)

**Comment by sjiang1** [comment]
How do you store the rating? Do you have a table for that? If so, please add this in the tasks.

**Comment by zxkevin** [comment]
The rating will currently be stored as a rolling average in the Captions table which will be create as part of #60

**Comment by 3dxp** [comment]
I updated the issue to reflect how we are going to implement the rankings, and added some notes about how rankings are not going to be a resource available on the API.

**Comment by 3dxp** [comment]
@sjiang1 we updated the endpoint name to `_rate` from rating to better denote it is an action instead of a resource. Is this change ok with you?
