### ISSUE TITLE
Implement POST /v1/users Endpoint 

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#62]
As a content creator, I want a page with my user info so that all who visit the webpage can view see my info.

**Tasks:**

- [x] Create controller for saving users
- [x] Create the route for POST /v1/users

**Acceptance Criteria:**
- When a POST request is made against the POST /v1/users endpoint with a JSON request body with a first name, last name and username, the resource is created, and persisted to the database. A response with the location header set with the relative URL of the created user with a success status code is returned to the client
- When a POST request body has a blank or missing username, first name or last name an error will be returned to the client in the response.
- When a POST request body has a username that already exists an error will be returned to the client in the response.
- When an invalid POST request is made against the /v1/users endpoint an error code is returned. (In the 400-499 HTTP response code.)

**Comment by sjiang1** [comment]
Add an acceptance criterion:
* if it succeeds, the first name, last name, username, and profile picture should be stored in a database
* the username for each user should be unique (the request will be denied if the new username already exists)

**Comment by zxkevin** [comment]
Added the ACs
